force-app/main/default/objects/PerformanceLog__c/PerformanceLog__c.object-meta.xml
<CustomObject>
    <description>This object logs performance related data</description>
    <label>PerformanceLog</label>
    <nameField>
        <displayFormat>PL-{0000000}</displayFormat>
        <label>PerformanceLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PerformanceLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PerformanceLog__c/fields/ApexClass__c.field-meta.xml
<CustomField>
    <fullName>ApexClass__c</fullName>
    <description>Apex Class Name</description>
    <label>Apex Class</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PerformanceLog__c/fields/ApexExecContext__c.field-meta.xml
<CustomField>
    <fullName>ApexExecContext__c</fullName>
    <label>Apex Exec Context</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PerformanceLog__c/fields/ApexMethod__c.field-meta.xml
<CustomField>
    <fullName>ApexMethod__c</fullName>
    <label>Apex Method</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PerformanceLog__c/fields/ApexSObject__c.field-meta.xml
<CustomField>
    <fullName>ApexSObject__c</fullName>
    <label>Apex SObject</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PerformanceLog__c/fields/CPU_Time_Used__c.field-meta.xml
<CustomField>
    <fullName>CPU_Time_Used__c</fullName>
    <label>CPU Time Used</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PerformanceLog__c/fields/CPUTime_Left_percentage__c.field-meta.xml
<CustomField>
    <fullName>CPUTime_Left_percentage__c</fullName>
    <label>CPUTime Left %</label>
    <precision>8</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PerformanceLog__c/fields/CPUTime_Limits__c.field-meta.xml
<CustomField>
    <fullName>CPUTime_Limits__c</fullName>
    <label>CPUTime Limits</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PerformanceLog__c/fields/Heap_Size_Left_percentage__c.field-meta.xml
<CustomField>
    <fullName>Heap_Size_Left_percentage__c</fullName>
    <label>Heap Size Left %</label>
    <precision>8</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PerformanceLog__c/fields/Heap_Size_Used__c.field-meta.xml
<CustomField>
    <fullName>Heap_Size_Used__c</fullName>
    <label>Heap Size Used</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PerformanceLog__c/fields/HeapSize_Limits__c.field-meta.xml
<CustomField>
    <fullName>HeapSize_Limits__c</fullName>
    <label>HeapSize Limits</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PerformanceLog__c/fields/IsCurrentContextTrigger__c.field-meta.xml
<CustomField>
    <fullName>IsCurrentContextTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsCurrentContextTrigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PerformanceLog__c/fields/Queries_Left_percentage__c.field-meta.xml
<CustomField>
    <fullName>Queries_Left_percentage__c</fullName>
    <label>Queries Left %</label>
    <precision>8</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PerformanceLog__c/fields/Queries_Used__c.field-meta.xml
<CustomField>
    <fullName>Queries_Used__c</fullName>
    <label>Queries Used</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PerformanceLog__c/fields/Query_Limits__c.field-meta.xml
<CustomField>
    <fullName>Query_Limits__c</fullName>
    <label>Query Limits</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PerformanceLog__c/fields/Quiddity__c.field-meta.xml
<CustomField>
    <fullName>Quiddity__c</fullName>
    <label>Quiddity</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/PerformanceLog__c/fields/RecordsInContext__c.field-meta.xml
<CustomField>
    <fullName>RecordsInContext__c</fullName>
    <label>Records In Context</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PerformanceLog__c/fields/RequestId__c.field-meta.xml
<CustomField>
    <fullName>RequestId__c</fullName>
    <label>Request Id</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/DataDog.cls
public class DataDog {
  public static String postLog(PerformanceLog__c pl) {

    String url = 'https://http-intake.logs.us5.datadoghq.com/api/v2/logs';
    String jsonBody = JSON.serialize(
    new Map<String, String> {
        'ddsource' => 'NA91 Developer Org',
        'ddtags' => 'env:NA91,version:1.0',
        'hostname' => 'Developer Org',
        'message' => String.valueOf(System.now())+'|This is a test',
        'service' => 'Custom Apex',
        'timestamp' => String.valueOf(System.now()),
        'user.name' => UserInfo.getName(),
        'user.id' => UserInfo.getUserId(),
        'user.profileId' => UserInfo.getProfileId(),
        'user.org_name' => UserInfo.getOrganizationName(),
        'user.orgId' => UserInfo.getOrganizationId(),
        'status' => 'Error',
        'trigger.object' => String.valueOf(pl.ApexSObject__c),
        'trigger.class' => String.valueOf(pl.ApexClass__c),
        'trigger.method' => String.valueOf(pl.ApexMethod__c),
        'trigger.execution_context' => String.valueOf(pl.ApexExecContext__c),
        'trigger.records_in_context' => String.valueOf(pl.RecordsInContext__c),
        'transaction.requestId' => String.valueOf(pl.RequestId__c),
        'limits.used.queries_used' => String.valueOf(pl.Queries_Used__c),
        'limits.used.cpu_time_used' => String.valueOf(pl.CPU_Time_Used__c),
        'limits.used.heap_size_used' => String.valueOf(pl.Heap_Size_Used__c),
        'limits.total.queries_total' => String.valueOf(pl.Query_Limits__c),
        'limits.total.cpu_time_total' => String.valueOf(pl.CPUTime_Limits__c),
        'limits.total.heap_size_total' => String.valueOf(pl.HeapSize_Limits__c),
        'limits.left(%).queries_left' => String.valueOf(pl.Queries_Left_percentage__c),
        'limits.left(%).cpu_time_left' => String.valueOf(pl.CPUTime_Left_percentage__c),
        'limits.left(%).heap_size_left' => String.valueOf(pl.Heap_Size_Left_percentage__c),
        'transaction.quiddity' => String.valueOf(pl.Quiddity__c),
        'transaction.is_CurrentContext_Trigger' => String.valueOf(pl.IsCurrentContextTrigger__c)
    });
    System.debug('JSON o/p:'+jsonBody);

    // Instantiate a new Http object
    Http h = new Http();

    // Instantiate a new HTTP request
    // Specify request properties such as the endpoint, the POST method, etc. 
    HttpRequest req = new HttpRequest();
    req.setEndpoint(url);
    req.setMethod('POST');
    req.setHeader('Content-Type', 'application/json');
    req.setHeader('Accept', 'application/json');
    req.setHeader('DD-API-KEY', 'c3d8b8bcae834ba11aa1a86186862d45');
    req.setBody(jsonBody);

    // Send the request, and return a response
    HttpResponse res = h.send(req);
    return res.getBody();
  }
}